version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=movil_api
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80

  app:
    container_name: node-app
    image: nodeapp
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      API_KEY: ${API_KEY}
      HASS_CICLES: ${HASS_CICLES}
      TOKEN_SECRET: ${TOKEN_SECRET}
    depends_on:
      - postgres
